CREATE DATABASE IF NOT EXISTS alquiler_canchas;
USE alquiler_canchas;


CREATE TABLE usuario (
id INT AUTO_INCREMENT PRIMARY KEY,
email VARCHAR(150) UNIQUE NOT NULL,
password VARCHAR(255) NOT NULL,
nombre VARCHAR(100),
apellido VARCHAR(100),
tipo_usuario ENUM('ADMIN','RECEPCIONISTA','ENCARGADO') DEFAULT 'RECEPCIONISTA'
);


CREATE TABLE cliente (
id INT AUTO_INCREMENT PRIMARY KEY,
nombre VARCHAR(100) NOT NULL,
apellido VARCHAR(100) NOT NULL,
dni VARCHAR(20) UNIQUE NOT NULL,
telefono VARCHAR(50),
email VARCHAR(150)
);


CREATE TABLE cancha (
id INT AUTO_INCREMENT PRIMARY KEY,
nombre VARCHAR(100) NOT NULL,
tipo ENUM('FUTBOL5','FUTBOL7','PADEL','TENIS') NOT NULL,
precio_hora DECIMAL(10,2) NOT NULL
);


CREATE TABLE horario (
id INT AUTO_INCREMENT PRIMARY KEY,
hora_inicio TIME NOT NULL,
hora_fin TIME NOT NULL
);


CREATE TABLE reserva (
id INT AUTO_INCREMENT PRIMARY KEY,
cliente_id INT NOT NULL,
cancha_id INT NOT NULL,
horario_id INT NOT NULL,
fecha DATE NOT NULL,
usuario_id INT,
estado ENUM('PENDIENTE','CONFIRMADA','CANCELADA') DEFAULT 'PENDIENTE',
FOREIGN KEY (cliente_id) REFERENCES cliente(id) ON DELETE CASCADE,
FOREIGN KEY (cancha_id) REFERENCES cancha(id) ON DELETE CASCADE,
FOREIGN KEY (horario_id) REFERENCES horario(id) ON DELETE CASCADE,
FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON DELETE SET NULL
);


CREATE TABLE pago (
id INT AUTO_INCREMENT PRIMARY KEY,
reserva_id INT NOT NULL,
monto DECIMAL(10,2) NOT NULL,
fecha_pago DATETIME DEFAULT CURRENT_TIMESTAMP,
metodo ENUM('EFECTIVO','DEBITO','CREDITO','TRANSFERENCIA') NOT NULL,
FOREIGN KEY (reserva_id) REFERENCES reserva(id) ON DELETE CASCADE
);